/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RNameJsonRouteImport } from './routes/r/$name.json'
import { Route as MacrosClassJsonRouteImport } from './routes/macros/$class.json'

const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RNameJsonRoute = RNameJsonRouteImport.update({
  id: '/r/$name/json',
  path: '/r/$name/json',
  getParentRoute: () => rootRouteImport,
} as any)
const MacrosClassJsonRoute = MacrosClassJsonRouteImport.update({
  id: '/macros/$class/json',
  path: '/macros/$class/json',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/registry': typeof RegistryRoute
  '/macros/$class/json': typeof MacrosClassJsonRoute
  '/r/$name/json': typeof RNameJsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/registry': typeof RegistryRoute
  '/macros/$class/json': typeof MacrosClassJsonRoute
  '/r/$name/json': typeof RNameJsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/registry': typeof RegistryRoute
  '/macros/$class/json': typeof MacrosClassJsonRoute
  '/r/$name/json': typeof RNameJsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/registry' | '/macros/$class/json' | '/r/$name/json'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/registry' | '/macros/$class/json' | '/r/$name/json'
  id: '__root__' | '/' | '/registry' | '/macros/$class/json' | '/r/$name/json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegistryRoute: typeof RegistryRoute
  MacrosClassJsonRoute: typeof MacrosClassJsonRoute
  RNameJsonRoute: typeof RNameJsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$name/json': {
      id: '/r/$name/json'
      path: '/r/$name/json'
      fullPath: '/r/$name/json'
      preLoaderRoute: typeof RNameJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/macros/$class/json': {
      id: '/macros/$class/json'
      path: '/macros/$class/json'
      fullPath: '/macros/$class/json'
      preLoaderRoute: typeof MacrosClassJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegistryRoute: RegistryRoute,
  MacrosClassJsonRoute: MacrosClassJsonRoute,
  RNameJsonRoute: RNameJsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
