/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as MacrosClassJsonRouteImport } from './routes/macros/$class.json'
import { Route as RNameJsonRouteImport } from './routes/r/$name.json'
import { Route as RegistryMediaAddonJsonRouteImport } from './routes/registry-media/$addon.json'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const MacrosClassJsonRoute = MacrosClassJsonRouteImport.update({
  id: '/macros/$class/json',
  path: '/macros/$class/json',
  getParentRoute: () => rootRouteImport,
} as any)
const RNameJsonRoute = RNameJsonRouteImport.update({
  id: '/r/$name/json',
  path: '/r/$name/json',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryMediaAddonJsonRoute = RegistryMediaAddonJsonRouteImport.update({
  id: '/registry-media/$addon/json',
  path: '/registry-media/$addon/json',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profiles': typeof ProfilesRoute
  '/registry': typeof RegistryRoute
  '/macros/$class/json': typeof MacrosClassJsonRoute
  '/r/$name/json': typeof RNameJsonRoute
  '/registry-media/$addon/json': typeof RegistryMediaAddonJsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profiles': typeof ProfilesRoute
  '/registry': typeof RegistryRoute
  '/macros/$class/json': typeof MacrosClassJsonRoute
  '/r/$name/json': typeof RNameJsonRoute
  '/registry-media/$addon/json': typeof RegistryMediaAddonJsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profiles': typeof ProfilesRoute
  '/registry': typeof RegistryRoute
  '/macros/$class/json': typeof MacrosClassJsonRoute
  '/r/$name/json': typeof RNameJsonRoute
  '/registry-media/$addon/json': typeof RegistryMediaAddonJsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profiles'
    | '/registry'
    | '/macros/$class/json'
    | '/r/$name/json'
    | '/registry-media/$addon/json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profiles'
    | '/registry'
    | '/macros/$class/json'
    | '/r/$name/json'
    | '/registry-media/$addon/json'
  id:
    | '__root__'
    | '/'
    | '/profiles'
    | '/registry'
    | '/macros/$class/json'
    | '/r/$name/json'
    | '/registry-media/$addon/json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfilesRoute: typeof ProfilesRoute
  RegistryRoute: typeof RegistryRoute
  MacrosClassJsonRoute: typeof MacrosClassJsonRoute
  RNameJsonRoute: typeof RNameJsonRoute
  RegistryMediaAddonJsonRoute: typeof RegistryMediaAddonJsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/macros/$class/json': {
      id: '/macros/$class/json'
      path: '/macros/$class/json'
      fullPath: '/macros/$class/json'
      preLoaderRoute: typeof MacrosClassJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$name/json': {
      id: '/r/$name/json'
      path: '/r/$name/json'
      fullPath: '/r/$name/json'
      preLoaderRoute: typeof RNameJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry-media/$addon/json': {
      id: '/registry-media/$addon/json'
      path: '/registry-media/$addon/json'
      fullPath: '/registry-media/$addon/json'
      preLoaderRoute: typeof RegistryMediaAddonJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfilesRoute: ProfilesRoute,
  RegistryRoute: RegistryRoute,
  MacrosClassJsonRoute: MacrosClassJsonRoute,
  RNameJsonRoute: RNameJsonRoute,
  RegistryMediaAddonJsonRoute: RegistryMediaAddonJsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
